### ISSUE TITLE
Undefined method `sum'

### ISSUE THREAD

**Issue by ruby232** [igrigorik/decisiontree#33]
I'm try run examples/simple.rb in master but throw this error:

```
entropy': undefined method `sum' for [2, 3, 1]:Array (NoMethodError)
```
Try gem version 0.5.0 and work find, maybe it introduced in pull request [#32](https://github.com/igrigorik/decisiontree/commit/846448acd635e192828da64eb0d17ab7435c45a2)

**Comment by ruby232** [comment]
Fix add 
```ruby
require 'active_support'
require 'active_support/core_ext'
```
but i guess it not best solution

**Comment by igrigorik** [comment]
Guessing, you're on an older version of ruby? 

This was introduced in https://github.com/igrigorik/decisiontree/commit/13aed0b2ae57e994e3366fedf15530d86c47bccd. /cc @cheerfulstoic

**Comment by ruby232** [comment]
My version of ruby is 2.3.1
```sh
└─ $ ▶ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by igrigorik** [comment]
Right, figures... Sum is 2.4+ http://blog.bigbinary.com/2016/11/02/ruby-2-4-introduces-enumerable-sum.html.

@cheerfulstoic I propose we revert the sum update until 2.3 is deprecated.

**Comment by cheerfulstoic** [comment]
Yep, sorry about that!  Just created #34 and #35

**Comment by cheerfulstoic** [comment]
(Was editing in the UI and I couldn't see a way to do it in one PR)
